### ISSUE TITLE
Kanban review

### ISSUE THREAD

**Issue by cwaku** [afizsavage/oracle-booking#11]
We are a team of 4 members.
Here is the link to the backend [kanban board](https://github.com/vic778/Oracle-booking-API/projects/1)

![image](https://user-images.githubusercontent.com/29071984/173349712-67764c1e-8ee6-4017-a2ad-867899d6795d.png)

**Comment by mosesogwo** [comment]
Good job dividing the task among the team...
[OPTIONAL] - include a full screenshot of your board here. You can zoom out to capture entire board.

**Comment by cwaku** [comment]
> Good job dividing the task among the team... [OPTIONAL] - include a full screenshot of your board here. You can zoom out to capture entire board.

Okay, Thank you. It has been done @mosesogwo
